# Constants, to avoid cluttering settings.py or another views file

WRONG_EMAIL_PASSWORD = "There is no user with that email and password."
INVALID_EMAIL = "Please enter a valid email address."
INVALID_PASSWORD = "Please enter a valid password."
PASSWORD_MISMATCH = "Please ensure that the passwords match."
EMAIL_ALREADY_EXISTS = "A user with that email address already exists."
WRONG_CURRENT_PASSWORD = "That's not the correct current password."
PROBLEM_NO_GENERATE = "There was an error generating the problem."
INVALID_QUESTION = "Please enter a valid question."
INVALID_ANSWER = "Please enter a valid answer."
INVALID_SKILL = "Please choose a valid skill."
NO_PROGRESS = "You are not logged in, so no progress will be saved!"
CORRECT_ANSWER = "Correct!"
INCORRECT_ANSWER = "Incorrect! The correct answer was %s."
INVALID_TITLE = "Please enter a valid title."
INVALID_BODY = "Please enter a valid text body."
INVALID_CODE = "Please enter a valid embed code."
INVALID_SCORE = "Please enter a valid integer score."
GENERIC_ERROR = "There was an error. Please try again later."
